import { Logger } from "@lib/logast.js"
import { DocUtils } from "@state/slices/doc/utils.js";
import { theDocManager } from "./DocManager.js";
import { MarkdownBuilder } from "@lib/mdbuilder.js";
import { path } from "@lib/path.js";
import { LibraryDoc } from "@state/slices/doc/types.js";

// status:
//   not_found: 文档不存在
//   error: 加载文档内容时出错
//   unchanged: 文档内容未改变，使用已有内容（仅当输入提供了旧signature时有效）
//   ok: 文档内容已加载
export type LoadDocResult = { 
  status: 'not_found' | 'error' | 'unchanged' | 'ok',
  // fail 时的错误信息
  error?: string,

  // ok/unchanged 时的返回值
  docPath?: string,   // 文档真实路径
  signature?: string, // 用于标识文件内容版本的签名
  content?: string    // 文件内容
};

// 加载文档内容
// docId 为全局文档ID， 详见 state/slices/doc/types.ts
// lastSignature: 可选的既有的文件签名，用于判断文件是否被外部修改
export async function loadDoc(docId: string, lastSignature?: string): Promise<LoadDocResult> {
  // 获取 Doc 对象，包含文档的元信息，应该要被准备好了
  const doc = DocUtils.getDocById(docId);
  if (!doc)
    return { status: 'not_found', error: `Document not found for docId: ${docId}` };

  // 先判断文档是否已被其他Tab打开(因此可能被编辑过尚未保存)，要优先用最新的文档内容
  const editorStates = theDocManager.getEditorStates(docId);
  const lastEditorState = editorStates && editorStates.length > 0 ? editorStates[0] : null;

  if (doc.origin === 'unsaved')
    return { status: 'ok', content: lastEditorState ? lastEditorState.doc.toString() : '' };

  /// library 文档 / external 文档，可能要从文件系统加载

  const docPath = DocUtils.docPath(doc)!;
  const stat = await window.fs.stat(docPath);

  if (!stat) {
    return { status: 'not_found', docPath,  error: `Document file not found at path: ${docPath}` };
  } else if (stat.isDirectory) {
    if (doc.origin !== 'library')
      return { status: 'error', docPath, error: `不支持打开非知识库的目录: ${docPath}` };
    const libDoc = doc as LibraryDoc;

    // 生成一个目录索引文档，文件名为 目录名.md (假的文件)
    // 文件内部的链接都是 @链接，以便用户可以点击打开子目录和文档
    const filePath = docPath.endsWith('/') ? docPath.slice(0, -1) + '.md' : docPath + '.md';
    const atLink = DocUtils.getAtLinkByLibraryDocId(docId)!;

    const items = await window.fs.listDir(docPath);
    const root = { level: 0, title: path.basename(filePath), children: [] };
    const builder = new MarkdownBuilder(filePath, root, root);

    // 把目录下的子项生成表格
    const headers = ['Name', 'Type', 'Size', 'Link'];
    const rows = Array<string[]>();
    for (const item of items) {
      const name = item.isDirectory ? item.name + '/' : item.name;
      const link = atLink + (atLink.endsWith('/') ? '' : '/') + item.name + (item.isDirectory ? '/' : '');
      const type = item.isDirectory ? 'Folder' : 'File';
      const size = item.isDirectory ? '-' : `${item.size} bytes`;

      rows.push([name, type, size, link]);
    }

    builder.heading(`Folder: ${atLink}`);
    builder.text('');
    builder.text(`Total ${rows.length} items.`);
    builder.table(headers, rows);
    builder.text('');
    builder.text('Generated by Eidux');
    builder.text('');
    const content = builder.asString();

    return { status: 'ok', docPath, content };
  } else {
    // 获取文件签名(仅判断大小/修改时间/创建时间等组合，并不读取文件内容并计算摘要)
    const signature = await window.fs.getFileSignature(docPath);

    // 如果有已打开的EditorState，且文件未在外部改变，则返回已有内容
    if (lastEditorState && lastSignature === signature) {
      Logger.debug('ChatEditor', `Document ${docId} is already opened in another tab and unchanged, reusing its state.`);
      return { status: 'unchanged', docPath, signature, content: lastEditorState.doc.toString() };
    }

    // 从文件系统加载文件内容，可能是新打开的，或外部已改变的
    try {
      const content = await window.fs.readText(docPath);
      return { status: 'ok', docPath, signature, content };
    } catch (err) {
      return { status: 'error', docPath, error: `Failed to read document file at path: ${docPath}` };
    }
  }
}
